# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(800, 600)
        login.setStyleSheet("#login_user:hover , #login_pwd:hover , #btn_login:hover , #btn_cancel:hover{\n"
"border-radius:10px;\n"
"background-color:gray;\n"
"color:white;\n"
"}\n"
"#login_user , #login_pwd , #btn_login , #btn_cancel{\n"
"border-radius:10px;\n"
"background-color:white;\n"
"}\n"
"\n"
"#label_2{\n"
"border-radius:30px;\n"
"background-color:white;\n"
"}\n"
"\n"
"#label{\n"
"border-radius:30px;\n"
"background-color:#cccccc;\n"
"}")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(260, 110, 471, 441))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 271, 441))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.login_user = QtWidgets.QLineEdit(login)
        self.login_user.setGeometry(QtCore.QRect(370, 240, 291, 31))
        self.login_user.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_user.setObjectName("login_user")
        self.login_pwd = QtWidgets.QLineEdit(login)
        self.login_pwd.setGeometry(QtCore.QRect(370, 290, 291, 31))
        self.login_pwd.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_pwd.setObjectName("login_pwd")
        self.btn_login = QtWidgets.QPushButton(login)
        self.btn_login.setGeometry(QtCore.QRect(370, 350, 113, 32))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/icons8-arrow-30.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_login.setIcon(icon)
        self.btn_login.setObjectName("btn_login")
        self.btn_cancel = QtWidgets.QPushButton(login)
        self.btn_cancel.setGeometry(QtCore.QRect(540, 350, 113, 32))
        self.btn_cancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icon/logout.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setObjectName("btn_cancel")
        self.label_3 = QtWidgets.QLabel(login)
        self.label_3.setGeometry(QtCore.QRect(300, 480, 401, 61))
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "帳務管理"))
        self.label_2.setText(_translate("login", "Money Manager"))
        self.login_user.setToolTip(_translate("login", "帳號"))
        self.login_user.setPlaceholderText(_translate("login", "帳號"))
        self.login_pwd.setToolTip(_translate("login", "密碼"))
        self.login_pwd.setPlaceholderText(_translate("login", "密碼"))
        self.btn_login.setText(_translate("login", "登入"))
        self.btn_cancel.setText(_translate("login", "取消"))
